# Generated by Django 5.0.3 on 2024-03-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/admin/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/doctor/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/user/', verbose_name='Photo'),
        ),
    ]
