# Generated by Django 5.0.3 on 2024-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_administrator_photo_doctor_photo_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='photo',
            field=models.ImageField(null=True, upload_to='admin/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(null=True, upload_to='doctor/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user/', verbose_name='Photo'),
        ),
    ]
