# Generated by Django 5.0.3 on 2024-04-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_administrator_photo_alter_doctor_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
