# Generated by Django 4.2 on 2024-05-02 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': '2. Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'Post Comment', 'verbose_name_plural': '3. Post Comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
