# Generated by Django 4.2 on 2024-04-16 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customuser_is_doctor_customuser_is_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=500, verbose_name='Chat name')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Group Chat',
                'verbose_name_plural': 'Group Chats',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='consultation', verbose_name='Photo')),
                ('files', models.FileField(upload_to='files', verbose_name='Files')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_user_1', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_user_2', to=settings.AUTH_USER_MODEL, verbose_name='Reciver')),
            ],
            options={
                'verbose_name': 'Private Chat',
                'verbose_name_plural': 'Private Chats',
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
