# Generated by Django 4.2 on 2024-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0002_concretechat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='files',
            field=models.FileField(null=True, upload_to='files', verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='photo',
            field=models.ImageField(null=True, upload_to='consultation', verbose_name='Photo'),
        ),
    ]
