# Generated by Django 4.2 on 2024-06-05 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_read_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
