# Generated by Django 4.2 on 2024-05-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': '1. Administrators'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'BaseUser', 'verbose_name_plural': '3. BaseUsers'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': '2. Doctors'},
        ),
    ]
