# Generated by Django 4.2 on 2024-05-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Consultation', 'verbose_name_plural': '1. Consultations'},
        ),
        migrations.CreateModel(
            name='ConsultationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=500, verbose_name='Diagnosis')),
                ('recommendation', models.TextField(blank=True, verbose_name='recommendation')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation', verbose_name='Consultation')),
            ],
        ),
    ]
