# Generated by Django 4.2 on 2024-05-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_consultation_options_consultationanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationanswer',
            options={'verbose_name': 'Consultation Answer', 'verbose_name_plural': '2. Consultation Answers'},
        ),
    ]
