# Generated by Django 4.2 on 2024-05-11 12:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultationanswer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationanswer',
            name='recommendation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
