# Generated by Django 4.2 on 2024-05-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_administrator_options_alter_customuser_options_and_more'),
        ('consultation', '0004_alter_consultation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Is Answered?'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to='user.doctor', verbose_name='Doctor'),
        ),
    ]
