# Generated by Django 4.2 on 2024-05-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_administrator_options_alter_customuser_options_and_more'),
        ('consultation', '0005_consultation_is_answered_alter_consultation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctor', verbose_name='Doctor'),
        ),
    ]
